# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Miguel Faria
email: miguel.faria@tecnico.ulisboa.pt
description: >- # this means to ignore newlines until "baseurl:"
  Come meet Miguel Faria, a dynamic PhD Researcher combining machine learning and robotics to create better and more understandable artificial life.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://miguel-faria.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: mik3_d3vil
github_username:  miguel-faria

# Build settings
# theme: minima
theme: minimal-mistakes-jekyll
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/tactile@v0.2.0
# remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "dirt"
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache
  # - jekyll/scholar

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
    - _posts/2024-01-25-welcome-to-jekyll.*
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

include: ["_pages"]

footer:
  links:
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/miguel-faria-34048142/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/mik3_d3vil"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/miguel-faria"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/mik3devil"